version: "3.9"

services:
  db:
    image: postgres:15
    container_name: project_postgres
    restart: always
    environment:
      POSTGRES_USER: projectuser
      POSTGRES_PASSWORD: projectpass
      POSTGRES_DB: projectdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
