
version: '3.8'

services:
  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: admin           
      POSTGRES_PASSWORD: Ers-Root@123 
      POSTGRES_DB: ers_db            
    ports:
      - "5432:5432"
    networks:
      - ers-network

networks:
  ers-network:

